# Generated by Django 4.0.6 on 2022-07-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plataforma", "0005_refeicao_opcao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refeicao",
            name="carboidratos",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="refeicao",
            name="gorduras",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="refeicao",
            name="proteinas",
            field=models.FloatField(),
        ),
    ]
