# Generated by Django 4.0.1 on 2022-01-18 17:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
        ("cursos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aulas",
            options={"verbose_name_plural": "Aulas"},
        ),
        migrations.AlterModelOptions(
            name="cursos",
            options={"verbose_name_plural": "Cursos"},
        ),
        migrations.AlterField(
            model_name="aulas",
            name="curso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cursos.cursos"
            ),
        ),
        migrations.CreateModel(
            name="NotasAulas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nota",
                    models.CharField(
                        choices=[
                            ("p", "Péssimo"),
                            ("r", "Ruim"),
                            ("re", "Regular"),
                            ("b", "bom"),
                            ("o", "Ótimo"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "aula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cursos.aulas"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Notas Aulas",
            },
        ),
        migrations.CreateModel(
            name="Comentarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comentario", models.TextField()),
                ("data", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "aula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cursos.aulas"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Comentarios",
            },
        ),
    ]
