# Generated by Django 4.0.3 on 2022-04-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_alter_jobs_options_alter_referencias_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobs",
            name="arquivo_final",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
